name: PR
on: push

jobs:
  job1:
    runs-on: ubuntu-20.04
    steps:
      - run: exit 1

  job2:
    runs-on: ubuntu-20.04
    steps:
      - run: exit 0

  job3:
    runs-on: ubuntu-20.04
    needs: [job1, job2]
    if: ${{ failure() }}
    steps:
      - run: echo 1 or more jobs failed
